# Generated by Django 5.1.2 on 2024-10-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['created_at']},
        ),
    ]
